### ISSUE TITLE
Add support for `Aggregate strategies`

### ISSUE THREAD

**Issue by ivarconr** [finn-no/unleash#102]
After using unleash for a while we see that we now have a lot of "aggregate strategies" implemented, such as "usersWithIdAndBetaUsers" etc. 

Instead of having all different combinations of strategies implemented in all clients we could provide a way to define aggregated strategies. This way we only need the simple strategies implemented in each client.

**Comment by ivarconr** [comment]
#1 The filter-pattern

A simple way to extend the current API with a strategies field. The current ` strategy` and `parameters` field would be deprecated in favour of a new `strategies` array containing all strategies associated with a feature toggles. The idea is that any toggle can be associated with one or more strategies. If the toggle is enabled with any of the associated strategies it should be considered **on**.

**Current format:**
```json
{
    "features": [
        {
            "name": "featureX",
            "description": "",
            "enabled": true,
            "strategy": "default",
            "parameters": {}
        },
        {
            "name": "featureY",
            "description": "",
            "enabled": true,
            "strategy": "ActiveForUserWithEmail",
            "parameters": {
                "emails": "me@mail.com"
            }
        }
    ]
}
```

***New API***
```
{
    "features": [
        {
            "name": "featureX",
            "description": "",
            "enabled": true,
            "strategy": "default",
            "parameters": {},
            "strategies": [
                {
                    "name": "some_strategy",
                    "parameters": {}
                }
            ]
        },
        {
            "name": "featureY",
            "description": "",
            "enabled": true,
            "strategy": "default",
            "parameters": {},
            "strategies": [
                {
                    "name": "some_strategy",
                    "parameters": {
                        "emails": "me@mail.com"
                    }
                }
            ]
        }
    ]
}
```

**Comment by sveinelo** [comment]
+1

Could "strategy" be dropped from the new API?

**Comment by ivarconr** [comment]
yes. But that should be a two-step iteration:
- iteration 1: introduce new field, and deprecate old one.
- iteration 2: remove the old field (not backward compatible).

**Comment by ivarconr** [comment]
we have decided to move forward with multiple strategies. Based on real-world usage of Unleash we feel the need ability to add multiple activation strategies for a feature toggle. To make it simple to understand and easy to use (and based on what people actually have asked for) all strategies should be OR from the client perspective, meaning that if a feature toggle is considered active with one strategy it should be considered enabled. 

TODO:
- [ ] Add support for the new format in API
- [ ] Add support for multiple strategies in the Admin UI
