### ISSUE TITLE
Event: Hacking night - 27.04.2016

### ISSUE THREAD

**Issue by ivarconr** [finn-no/unleash#113]
This event will happen in Oslo and is open to everyone who wants to contribute. 

The agenda is to plan the next iteration of Unleash and start working on it.

Some topics already agreed on:
- add documentation
- convert flux to redux
- use React material-ui components. http://www.material-ui.com/#/components/toggle
- upgrade to react v15

Time: 27.04.2016 at 16:00-18:00
Location: FINN.no ("Grensen 5-7" in Oslo)

**Organizers:**
@ivarconr
@sveisvei 
@Andersos

**Comment by ivarconr** [comment]
ping @jarib @gardleopard @sveinelo @eirslett

**Comment by sveinelo** [comment]
Putting it in my calendar now.

**Comment by ivarconr** [comment]
Cool :)

**Comment by ivarconr** [comment]
We laid out a short term plan for unleash development and dived tasks among participants.
