### ISSUE TITLE
Stateless functions

### ISSUE THREAD

**Issue by ev1stensberg** [finn-no/unleash#114]
Ser mye av components ikke bruker `this`. Mulig at dere booster perf med et par hakk om dere bytter ut React classes med stateless functions 😄

**Comment by ivarconr** [comment]
Det har du nok helt rett i! =) 

Vi har begynt å planlegge neste versjon og et av teamene der er å rydde opp react-koden (react v15, redux, osv). Vi starter arbeidet allerede neste onsdag (#113), hiv deg gjerne på om du har mulighet/lyst.

**Comment by ev1stensberg** [comment]
Bare skriv her når dere starter du, så kan det nok ordnes ! Ha en god søndag 😄
