### ISSUE TITLE
Add a heroku deploy button

### ISSUE THREAD

**Issue by Andersos** [finn-no/unleash#120]

**Comment by Mause** [comment]
This would really useful - was there a reason why this issue was closed?

**Comment by ivarconr** [comment]
We decided to just trigger deployment on every change on the master branch. This has proven valuable multiple times, where errors are discovered fast.

**Comment by Mause** [comment]
This doesn't help people who want to deploy their own instances, which is the main reason why projects implement the "Deploy to Heroku" button - they just need to click a button, and an instance of the app is provisioned in their own Heroku account, along with the plugins/addons required to run it

**Comment by ivarconr** [comment]
Aha, thanks for clearing that out. 

I see no reason not to add this feature then.

**Comment by ivarconr** [comment]
Thanks for your feedback. I have added the button now, was really easy as stuff almost always are with Heroku :heart: .

We might need to offer some kind of configuration in the future when the auth-pr is merged and we release v3.  Any suggestion on how that could work would be awesome!

**Comment by Mause** [comment]
Um, there's a little bit more to it than a simple link - see the documentation here -> https://devcenter.heroku.com/articles/heroku-button

**Comment by Mause** [comment]
The link needs to include a query parameter pointing to the repository, I think?

**Comment by Mause** [comment]
Oh, wow, ok. Is it just based on the Referrer. My bad!

**Comment by Mause** [comment]
Thank you for the awesome project, I look forward to using it :)
