### ISSUE TITLE
Multi-module it

### ISSUE THREAD

**Issue by ivarconr** [finn-no/unleash#135]
To make `unleash` more modular i suggest that we look into using lerna (to keep single repo) and multimodularize our project into the following:

- unleash-server
- unleash-frontend
- unleash-docker

The main benefit is to make unelash easier to work with, and have a better separation of concern. 

 I am also thinking that we should pull out database-implementations and make them optional, but this should be done after the inital modularisation, this will also require us to adopt a database adapter pattern, discussed in #132 

- unleash-db-postgres

**Comment by ivarconr** [comment]
And we should probably also consider to move the clients to this project. We currently have:

- unleash-client-java
- unleash-client-node

What do you think @sveisvei ?

**Comment by sveisvei** [comment]
Yes! I think all the things that is needed (core setup) should be here.

**Comment by ivarconr** [comment]
Could we start introducing three first modules first (api, frontend and docker). I suspect this can be done without too much changes (and probably even keep `npm run start` from the parent project to support possible existing users. 

I suspect we should be able to this directly on master in one commit (probably via a small PR)

**Comment by sveisvei** [comment]
Sounds good, yeah lets see how this feels.
