### ISSUE TITLE
Subscriber details

### ISSUE THREAD

**Issue by ivarconr** [finn-no/unleash#154]
Today you just have to know which strategies a client (application) supports. This makes it hard to know what you can use in different clients. 

A nice solution to this would be to have all clients register to unleash server with metadata such as:
- app-name
- instance-id (could be a generated uid or a application provided id, pod-name or similar)

This could then be used by unleash-admin to visualize connected clients and what they support. 

relates to #124

**Comment by sveisvei** [comment]
Indeed it relates to 124, as this should/could be metadata in the same payload.

**Comment by ivarconr** [comment]
Obviously the `instance-id`should be the same! This would make it easy to see which apps receives traffic for a given feature toggle.

**Comment by ivarconr** [comment]
Also added clientIp, in case app-name or instance-id is missing.
