### ISSUE TITLE
Boost profile image fetching significantly

### ISSUE THREAD

**Issue by ivarconr** [finn-no/unleash#161]
Bause fetching a profile requres the current profile-service to also talk with the user-service we get a significant hit in percentile values for this service. 

Currently we are just interested in the profile image, and it is already available as a special methiod [getProfileImages](https://github.schibsted.io/finn/profile-client-node/blob/master/index.js#L32), this method will be much faster, becuase the profile service is not required to talk with other services for this call. 

Can we add a special resolver for the profile-image, so that we can skip resolving the whole client when only the image is requested?

**Comment by SimenB** [comment]
Why does unleash care about profile images at all? Especially finn internal thrift services

**Comment by ivarconr** [comment]
Wrong repo ;)

**Comment by SimenB** [comment]
Ah, finnlet. Gotcha!
