### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by Andersos** [finn-no/unleash#33]
We need to support some user authentication.
Passport (http://passportjs.org/) looks nice and we might have to make a SPID passport  provider if we want to use SPID for authentication.

**Comment by ivarconr** [comment]
I have started looking in to this.

**Comment by Andersos** [comment]
Im not sure https://github.com/finn-no/unleash/pull/79 really closes this. We might have to get some requirements from @kjartis about the authentication requirements for Unleash.

**Comment by ivarconr** [comment]
your probably right. I was a bit fast on the closes message.

**Comment by Andersos** [comment]
After the meeting this is the latest status (ref https://github.com/finn-no/unleash-client-java/issues/18):
You should always be able to turn on or off toggles even if the authentication provider is down.
Ideally everyone that dose a change need to be logged by name.
We will investigate using basic auth and having Crowd as the user provider.

**Comment by Andersos** [comment]
So was basic auth ever added?

**Comment by ivarconr** [comment]
not yet.
