### ISSUE TITLE
Improve service unit-tests

### ISSUE THREAD

**Issue by ivarconr** [finn-no/unleash#59]

**Comment by Andersos** [comment]
So what is the status here?

**Comment by jarib** [comment]
I made some improvements in #66, which has been merged. But the way this issue is worded, it's not very easy close - it's very unlikely the tests ever will reach a state of perfection :)

**Comment by ivarconr** [comment]
I suggest closing this issue and instead find concrete cases we feel needs better coverage.

**Comment by Andersos** [comment]
:+1:
