### ISSUE TITLE
Url with space

### ISSUE THREAD

**Issue by Andersos** [finn-no/unleash#77]
@runeh pointed out that the Feature Toggles page has a space in the url:
http://ci.rest.finn.no/unleash/#Feature Toggles

**Comment by jarib** [comment]
Is it a problem?

**Comment by ivarconr** [comment]
Not a big problem, but it is incorrect and makes it look silly when you want to share the link.

**Comment by runeh** [comment]
It makes life hard for linkfiers, like when hipchat tries to make a link out of the URL. Its regex terminates at the space.

**Comment by Andersos** [comment]
:+1:
