### ISSUE TITLE
Inconsistent event names

### ISSUE THREAD

**Issue by runeh** [finn-no/unleash#80]
feature-revived, feature-created and feature-updated are past tense. feature-archive is imperativ. Should probably be consistent.

**Comment by Andersos** [comment]
So the list of "actions" is the following:

feature-created
feature-updated
feature-archive
feature-revive
strategy-created
strategy-deleted

Do you have a suggestion for what they should be called?

**Comment by runeh** [comment]
Change feature-archive to feature-archived and feature-revive to feature-revived. Then they are all consistently named.

**Comment by Andersos** [comment]
Should be fixed now.
