### ISSUE TITLE
Document the creation and use of a local database on Mac

### ISSUE THREAD

**Issue by Andersos** [finn-no/unleash#89]
Ref https://github.com/finn-no/unleash-client-java/issues/18
I will try and do a write-up of how to setup a local database on Mac.

**Comment by stigkj** [comment]
Maybe we should include how to do this through Docker, too?

**Comment by Andersos** [comment]
I'm not familiar with how this can be run with Docker but documentation never helps. I suggest we open a separate issue for that. Maybe @gardleopard can help write something about how to run it.
