### ISSUE TITLE
Option to always activate for employees regardless of strategy

### ISSUE THREAD

**Issue by Andersos** [finn-no/unleash#94]
So I was talking with team PR and we agree there should be a way to always activate a feature for employees regardless of strategy. 

An example:
Lets say you are rolling out a new feature you want to test to only 10%.
It could be valuable for employees to come with feedback.
It will be harder for the support team to reproduce errors that are caused by the rollout. 

We could include an extra checkbox per feature that says if you want to include the employees in enabled feature list. 

Any thoughts on this?

**Comment by ivarconr** [comment]
I think this is related to the gradual-roll-out strategy. It makes perfect sense that gradual rollout also have list of specific userIds and/or options for roll-out to all employees. I do not think this is relevant for all the other strategies as they are much more limited (eg: activeForUse, byHost, byRemoteAddress etc).

**Comment by Andersos** [comment]
Agree with you on that. Maybe it is sufficient for this feature to be part of the gradual-roll-out strategy.

**Comment by ivarconr** [comment]
Yes
