### ISSUE TITLE
Extend the unleash interface with context-data

### ISSUE THREAD

**Issue by ivarconr** [finn-no/unleash#99]
In the current version of Unleash strategies needs to get their context data via special provides which typically is implemented as some magic-data available at the current request. This works well in most java-based web-applications. 

However doing toggles in a standalone web-application this becomes much harder as you typically do not have a user bound to the current request. In this scenario you will typically have the context-data available runtime, at the same location you want to verify if a toggle should be on or of. 

It would thus be beneficial if the client also could inject context data at runtime. The unleash API would then be overloaded with a new method, the the user can inject the required context-data. 

``` java
unleash.isEnabled("app.someToggle", UnleashConext.of("k1", "v1", "k2", "v2"));
```

Unleash will then in turn inject the context-data to the strategy which would be extended to:

``` java
public interface Strategy {
    String getName();

    boolean isEnabled(Map<String, String> parameters);

    boolean isEnabled(Map<String, String> parameters, UnleashConext context);
}
```

(\* if we move the client to java8 we could also provide a default implementation of the new method to avoid breaking the API)

This is also the approach used for the [unleash-client-node](https://github.com/finn-no/unleash-client-node).

**Comment by sveinelo** [comment]
I think newcomers to unleash, who needs to implement a new strategy, would always use UnleashContext if we introduce it, since it's more straight forward. Using UnleashContext is way better thatn using ThreadLocal IMHO.

I'm still a bit sceptic though. Could you give a concrete example when injecting a provider into the strategy would not solve the need for runtime data?

**Comment by ivarconr** [comment]
moved discussion to the java-client: https://github.com/finn-no/unleash-client-java/issues/29
